project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "nmfs-ost.github.io/PAM_towed_array/" 
  repo-url: "https://github.com/nmfs-ost/PAM_towed_array"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-ost.github.io/PAM_National_NMFS_Network
        text: "NMFS National Passive Acoustic Monitoring Network"
      - icon: github
        href: https://github.com/nmfs-ost/PAM_towed_array
        text: "NMFS PAM Towed Arrays"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: content/arrayModel.qmd
        contents: 
          - href: content/arrayModel_modular.qmd
            text: Modular Array
          - href: content/history.qmd
            text: Historical Arrays
      - section: content/Hardware.qmd
        text: Hardware
        contents: 
          - href: content/hydrophones.qmd
            text: Hydrophones
          - href: content/depth.qmd
            text: Depth
          - href: content/Inventory.qmd
            text: Inventory
      - section: content/lab.qmd
        contents: 
          - href: content/PI_LabSetup_1.qmd
            text: PIFSC Lab Bench
          - href: content/NEFSC_lab_setup.qmd
            text: NEFSC Lab Bench
      - section: content/FieldMethods.qmd
        text: Field Methods
        contents: 
          - href: content/NEFSC_towed_array_manual.qmd
            text: NEFSC
          - href: content/Array_details.qmd
            text: Array details
          - href: content/Real-time_SpeciesGuides.qmd
            text: Species Guides
      - section: content/Software.qmd
        text: Software
        contents: 
          - href: content/Pamguard_tips_tricks.qmd
            text: PAMGuard tips
          - href: content/NMFS_Logger_Forms.qmd
            text: Logger Forms
          - href: content/Real-time_QAQC.qmd
            text: QAQC
      - section: content/sop.qmd
        contents: 
       #   - href: content/xxx.qmd
        #    text: xxx
         # - section: content/sop/ne/sop_ne.qmd
          #  contents:
           # - href: content/sop/ne/page1.qmd
            #  text: Sidebar Name 
      - section: content/troubleshoot.qmd
        contents: 
          - href: content/xxx.qmd
            text: xxx
          - href: content/yyy.qmd
            text: yyy

        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
